### ISSUE TITLE
TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by moemar** [CrystallizeAPI/crystallize-frontend-boilerplate#7]
I get this error when trying to follow the guide, something I have done wrong?

`TypeError: Cannot read property 'map' of null
    at Object.children (C:\Projects\Privat\Crystallize\MyShop\.next\server\static\development\pages\index.js:1776:538)
    at finish (C:\Projects\Privat\Crystallize\MyShop\node_modules\react-apollo\react-apollo.cjs.js:354:55)
    at Query.render (C:\Projects\Privat\Crystallize\MyShop\node_modules\react-apollo\react-apollo.cjs.js:358:16)
    at processChild (C:\Projects\Privat\Crystallize\MyShop\node_modules\react-dom\cjs\react-dom-server.node.development.js:2959:18)
    at resolve (C:\Projects\Privat\Crystallize\MyShop\node_modules\react-dom\cjs\react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (C:\Projects\Privat\Crystallize\MyShop\node_modules\react-dom\cjs\react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (C:\Projects\Privat\Crystallize\MyShop\node_modules\react-dom\cjs\react-dom-server.node.development.js:3161:29)
    at renderToString (C:\Projects\Privat\Crystallize\MyShop\node_modules\react-dom\cjs\react-dom-server.node.development.js:3646:27)
    at render (C:\Projects\Privat\Crystallize\MyShop\node_modules\next-server\dist\server\render.js:81:16)
    at renderPage (C:\Projects\Privat\Crystallize\MyShop\node_modules\next-server\dist\server\render.js:230:20)
    at ctx.renderPage (C:\Projects\Privat\Crystallize\MyShop\.next\server\static\development\pages\_document.js:1644:26)
    at _callee2$ (C:\Projects\Privat\Crystallize\MyShop\.next\server\static\development\pages\_document.js:942:24)
    at tryCatch (C:\Projects\Privat\Crystallize\MyShop\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Projects\Privat\Crystallize\MyShop\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Projects\Privat\Crystallize\MyShop\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Projects\Privat\Crystallize\MyShop\.next\server\static\development\pages\_document.js:294:24)`

**Comment by hakonkrogh** [comment]
Hi. I tried the latest boilerplate, and could not replicate the error. Can you provide some more information? Which path did it happen? Is it server side or client side?

**Comment by hakonkrogh** [comment]
Fixed in #9
